CREATE TABLE "USER"
(ID BIGINT DEFAULT 0 NOT NULL,
ACTIVITIONCODE VARCHAR(64),
ACTIVE CHAR(2),
DISPLAYNAME VARCHAR(40),
EMAIL VARCHAR(100),
GEBURTSTAG VARCHAR(20),
NACHNAME VARCHAR(100),
PASSWORD VARCHAR(100),
USERNAME VARCHAR(40),
VORNAME VARCHAR(100),
ARSCH CHAR(1),
PRIMARY KEY (ID))